### ISSUE TITLE
Use linter exit code to determine check result

### ISSUE THREAD

**Issue by larsklevan** [samuelmeuli/lint-action#10]
I tried out the `rubocop` linter in my project and I noticed that when I have warnings:
<img width="739" alt="Screen Shot 2020-01-06 at 4 14 32 PM" src="https://user-images.githubusercontent.com/11699/71853063-eea5d480-309f-11ea-9c6c-e64e7b9cb7a3.png">

I still get a green check:
<img width="503" alt="Screen Shot 2020-01-06 at 4 14 24 PM" src="https://user-images.githubusercontent.com/11699/71853053-eb124d80-309f-11ea-8623-f93f7bb40bd3.png">

That's not the way that the typical `rubocop` setup works, usually those errors would return a non-zero exit code and fail the build. I wouldn't even know I needed to look for errors unless I click into the Detail screen.

I noticed that here you're only considering `errors` in the Check status:
https://github.com/samuelmeuli/lint-action/blob/a838ab16415bb1752bb9d77b4ce13fa80bfcaef6/src/github.js#L75

Would you consider failing on warnings as well? Or make that configurable?

**Comment by samuelmeuli** [comment]
It probably makes sense to use the linter's exit code to determine the check `conclusion`.

I've been considering adding a `[linter]_args` opition anyway, which would also make sense in this situation. It would allow users to change what types of offenses RuboCop returns a non-zero exit code for (with the `--fail-level` flag).

**Comment by larsklevan** [comment]
> It probably makes sense to use the linter's exit code to determine the check conclusion

I like this approach. Seems like it would be consistent with the way CI typically works.

**Comment by samuelmeuli** [comment]
Unfortunately, not all tools use a non-zero exit code when issues are found (e.g. `gofmt` doesn't). For these tools, the Lint Action should continue using the number of lint errors to determine the check status.

**Comment by larsklevan** [comment]
Yeah, it looks like `gofmt` is a bit of an oddball:
https://github.com/golang/go/issues/24230

**Comment by larsklevan** [comment]
Thank you for the quick fix! I tried it with `rubocop` in my project and it's working great.
