### ISSUE TITLE
Add `[linter]_args` option

### ISSUE THREAD

**Issue by samuelmeuli** [samuelmeuli/lint-action#11]
This option could allow users to pass additional command-line arguments to the linting command. E.g. useful if users want GitHub checks to fail if there are warnings (see https://github.com/samuelmeuli/lint-action/issues/10).

**Comment by nocalla** [comment]
Would this also allow configuration of linters? E.g. adding a line-length arguement to black?

**Comment by samuelmeuli** [comment]
Yes, but I think it's better to use a configuration file instead. That way, your options are applied both in CI and when runnung Black locally.

**Comment by nocalla** [comment]
Good point.
