### ISSUE TITLE
Overview of result in the Check output title

### ISSUE THREAD

**Issue by larsklevan** [samuelmeuli/lint-action#12]
Right now the linter Check is re-using the linter name for the output `title` which results in a view like this:
<img width="681" alt="Screen Shot 2020-01-08 at 3 39 44 PM" src="https://user-images.githubusercontent.com/11699/72018359-1d04ea80-322d-11ea-9ffe-adb3e2b23402.png">

A more typical `title` would include a summary of the results:
<img width="669" alt="Screen Shot 2020-01-08 at 3 36 35 PM" src="https://user-images.githubusercontent.com/11699/72018209-d6af8b80-322c-11ea-8c47-0ffe1c0f2b77.png">

I'd suggest something like "No errors found" or "1 error and 2 warnings" etc as the Check `title`. Might work to use the same value you're using for `summary` now.

**Comment by samuelmeuli** [comment]
Good idea 👍

**Comment by samuelmeuli** [comment]
New check titles:

<img width="744" alt="screenshot 2020-01-09 at 10 45 22" src="https://user-images.githubusercontent.com/22477950/72056732-715fa700-32cd-11ea-8c5d-3b78765dd2f9.png">

**Comment by larsklevan** [comment]
Thanks @samuelmeuli! Ready for version `0.8.0`? ;)

**Comment by samuelmeuli** [comment]
[Released](https://github.com/samuelmeuli/lint-action/releases/tag/v0.7.1) :)

**Comment by jsit** [comment]
@samuelmeuli How do you get it so that the main "Run linters" check doesn't show up in that list?
