### ISSUE TITLE
Action should only run `git push` if an auto-fix commit was created

### ISSUE THREAD

**Issue by larsklevan** [samuelmeuli/lint-action#14]
In [this code](https://github.com/samuelmeuli/lint-action/blob/53ebe1d2b97f8bedb6ca5ce1cb2d26193c0ca535/src/index.js#L72) `pushChanges` is triggered even if there are no new commits. I've noticed a couple of issues with this:
* it re-creates deleted branches
* it can cause an error if the branch has been updated since the build started, even if there is no autofix

Would be nice to trigger a `git push` only if there are new commits. And ideally the `git push` would quietly fail if the branch has been updated since presumably a new run will be triggered.

Sample log of ESLint bombing on `push` without any changes:
<img width="812" alt="Screen Shot 2020-01-24 at 11 38 39 AM" src="https://user-images.githubusercontent.com/11699/73090649-60eb2700-3e9e-11ea-9cba-656b3d78050a.png">

**Comment by samuelmeuli** [comment]
Thanks for reporting! This behavior should definitely be changed.
