### ISSUE TITLE
linters falsely passing in 1.1.0

### ISSUE THREAD

**Issue by larsklevan** [samuelmeuli/lint-action#19]
After upgrading from 0.7.9 to 1.1.0 our team noticed that some lint violations had crept in. They were all `autofixable` so I'm wondering if the diff detection is not working?

0.7.9:
```
Verifying setup for RuboCop…
Verified RuboCop setup
Will use RuboCop to check the files with extensions rb
Linting and auto-fixing files in /home/runner/work/project/project with RuboCop…
RuboCop found no issues (success)
Committing changes
Pushing changes to ***github.com/company/project.git
To https://github.com/company/project.git
```

It's not obvious from the log in 0.7.9 but it did push an autofix commit.

1.1.0:
```
Verifying setup for RuboCop…
Verified RuboCop setup
Will use RuboCop to check the files with extensions rb
Linting and auto-fixing files in /home/runner/work/project/project with RuboCop…
RuboCop found no issues (success)
```

In 1.1.0 no autofix commit was pushed

**Comment by samuelmeuli** [comment]
Probably a duplicate of #18. I've released a fix a few minutes again. Could you please try rerunning your workflow? :)

**Comment by larsklevan** [comment]
You're right - verified that 1.2.0 fixes it!
