### ISSUE TITLE
Error when using action with GatsbyJS

### ISSUE THREAD

**Issue by daniel-vc** [samuelmeuli/lint-action#30]
Hi there, 

I'm trialling this action with the default ESLint setup that comes with GatsbyJS, and i'm receiving the below error. Any idea's or is this a bug?

<img width="831" alt="Screenshot 2020-03-16 at 11 28 24" src="https://user-images.githubusercontent.com/39903900/76754157-8cd9a900-6779-11ea-9c95-db74555b424f.png">

[Here](https://github.com/gatsbyjs/gatsby/blob/master/.eslintrc.js) is a link to their eslint file

Thanks!

**Comment by daniel-vc** [comment]
Passing eslint_args="--no-eslintrc" seemed to help with this error.

I think that's because this action might check for eslint config files first but gatsby doesn't provide a .eslintrc file. Might be worth fixing this so that the action doesn't rely on a .eslintrc file existing?

**Comment by daniel-vc** [comment]
What I'm getting now is the below. So the action seems to be working. What I'd like to know though, is some sort of output as to what 2 errors it's found so that i can fix. (Without the action auto fixing).  I'm also not getting any eslint error's locally, so this is proving hard to fix. Maybe the default gatsby rules aren't the same as the rules you use?

<img width="996" alt="Screenshot 2020-03-16 at 12 08 26" src="https://user-images.githubusercontent.com/39903900/76757218-2192d580-677f-11ea-86ae-b9ca947bec3f.png">

**Comment by samuelmeuli** [comment]
> Passing eslint_args="--no-eslintrc" seemed to help with this error.

> I think that's because this action might check for eslint config files first but gatsby doesn't provide a .eslintrc file. Might be worth fixing this so that the action doesn't rely on a .eslintrc file existing?

What's the recommended way to run ESLint in your Gatsby setup? Maybe it's not with the `eslint` command, which is what this action runs internally. It's not the action that looks for a config file, it's ESLint itself.

> Maybe the default gatsby rules aren't the same as the rules you use?

This action doesn't specify any linting rules. It only runs ESLint for you.

**Comment by daniel-vc** [comment]
Hey @samuelmeuli thanks for the response. 

So all that's required is to have babel-eslint and eslint packages as devDependencies in package.json

**Comment by samuelmeuli** [comment]
But how do you run the linter? Is there a script in `package.json`?

**Comment by daniel-vc** [comment]
No. Gatsby handles it all with their eslint-loader
See this page: https://www.gatsbyjs.org/docs/eslint/

**Comment by samuelmeuli** [comment]
So ESLint isn't called as a command, but probably via the Node.js API as part of the Webpack build process. This would explain why it works without a configuration file.

If you configure ESLint with a file, as described in the link you posted, the action will probably succeed.
