### ISSUE TITLE
Select a list of Directories / files

### ISSUE THREAD

**Issue by eMerzh** [samuelmeuli/lint-action#54]
Hello,

thanks for this action

I wanted to run flake8 and black but it seems that for some reason he try to lint/format all my deps in a folder called "<some random uuid>/lib/python....." not sure why....

to avoid that i looked at a way to select the list of directories and files to run on but seems the _dir does not do the job with multiple input

is there a better way?

**Comment by samuelmeuli** [comment]
See #46
