### ISSUE TITLE
Checks overwritten when action is used in different folders

### ISSUE THREAD

**Issue by LeticiaErrandonea** [samuelmeuli/lint-action#61]
Hello.

First of all, thanks for the project!

I have a monorepo with two folders: `app` and `server`. I have a workflow for the app and another one for the server because the config is different.

When running the workflows, I noticed the following:
* The app one has an output with errors but is successful (neither `ESLint` nor `Prettier` cjecks are created).
* The server one doesn't have errors but fails (both `ESLint` and `Prettier` checks are created).
* All errors listed in the `ESLint` check (created when running the server one) belong to the `app` folder.

![image](https://user-images.githubusercontent.com/28798610/85348151-17484c00-b4d1-11ea-9931-0f6c7533910b.png)

Because running only one of the workflows behaves as expected, I know that the workflows are properly set. 

The server workflow is running first, so I think the issue is that, when the app workflow runs, `ESLint` and `Prettier` checks get overwritten.

Is there any workaround? 

I think a way of solving it could be accepting an optional input to set the name for the created checks. Let me know if this sounds good and I can open a PR.

Thanks!

**Comment by ocean90** [comment]
Hi @LeticiaErrandonea, thank you for the detailed report! I tried a few things but adding an action input for the `check_name` seems to be the best option here. See #83 for the suggested changes. What do you think?

**Comment by LeticiaErrandonea** [comment]
Hi, @ocean90! 

That looks great.

Thanks for looking into it!
