### ISSUE TITLE
Add support for `pull_request` events

### ISSUE THREAD

**Issue by SimenB** [samuelmeuli/lint-action#9]
Probably something I messed up...

![image](https://user-images.githubusercontent.com/1404810/71786496-3f6bed80-300c-11ea-8e74-9e21c5321fa1.png)

Both eslint and prettier says they found an error, but the step didn't fail and no annotation was added.

From https://github.com/facebook/jest/pull/9367

**Comment by samuelmeuli** [comment]
The problem is that the action is executed on the `pull_request` event, which it doesn't support yet (only the `push` event, which lets the action easily determine which commit needs to be annotated).

I'm planning to fix this though :)

**Comment by SimenB** [comment]
Ah, that makes sense. It should fail the step regardless though, no? Or maybe just explode if ran on an unsupported event altogether

**Comment by samuelmeuli** [comment]
> Or maybe just explode if ran on an unsupported event altogether

Yeah, I expected this to be the current behavior, but it looks like I removed the check at some point 😅 I'll add it back as a temporary solution and will think about how the `pull_request` event could be supported.

**Comment by samuelmeuli** [comment]
Released in [v0.6.0](https://github.com/samuelmeuli/lint-action/releases/tag/v0.6.0)

**Comment by SimenB** [comment]
Oh, that was quick! Thanks 🎉

**Comment by kevgliss** [comment]
Is v0.6.0 available on the marketplace? It looks like it's marked as pre-release, and I'm running into issues attempting to use the [pull_request] action: 

https://github.com/Netflix/dispatch/blob/develop/.github/workflows/list_and_test.yml

Thanks!
